### ISSUE TITLE
Minbpe as a potential course 

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [karpathy/minbpe#19]
I thoroughly enjoy Karpathy's YouTube content; it's consistently top-notch. I've been wondering whether this could potentially evolve into a concise course on platforms like Coursera or edX. The content he provides, usually around two hours long, is substantial, and I've noticed the inclusion of coding exercises for Minibpe. If complemented with quizzes, it could transform into a robust course. At the same time, I understand that organizing and setting up a course requires additional effort. 

We could explore a dedicated platform, akin to deeplearning.ai, which could be worth considering. I felt compelled to share this thought.

Moreover, a considerable number of people might be willing to contribute their time and efforts to help build such a platform(open-source), considering the extensive reach and impact of his video content.

I'm curious to hear the thoughts of others on this matter.

**Comment by ViswanathaReddyGajjala** [comment]
I intend to close this issue within the next 24 hours.

**Comment by karpathy** [comment]
I don't know I don't really like these platforms too much and they usually irritate me with dark patterns when I stop by. I don't want to sign up for anything, I just want the content. I don't want to "enroll" in anything, I just want the content. I don't want to be pestered with engagement or marketing email afterwards. [Zero To Hero](https://karpathy.ai/zero-to-hero.html) is already several "lectures" in, and most have exercises in the comments, there is a Discord community all learning together which is a bit like the discussion boards. Forget existing platforms what is the ideal experience you'd want to see and that you're missing?

**Comment by karpathy** [comment]
Sure, if you can help with any of the above I'm happy to link to it. Ty!
