### ISSUE TITLE
`regex.py` is feature-engineering and will probably degrade performance when scaling to many languages

### ISSUE THREAD

**Issue by domschl** [karpathy/minbpe#31]
`regex.py` contains many assumptions that 

- only make sense for English (all apostrophe rules `(?i:[sdmt]|ll|ve|re)`)
- only make sense for some Western languages (roles of 'words', 'blanks')

The equivalent for image recognition would be to invest effort in 'arm'- and 'legs'-feature-detects. And then the thing needs to recognize a sphere...

Eastern languages do not use blanks to separate what the West calls 'words'. Some have syllable breaks (and syllables are not words), some have characters that are near equivalents to word-syllables and no work-breaks at all.
Some Western languages make heavy use of compound words (with no separators) or have far more complex grammatical morphing rules than English.

Recommendation: remove regex, or at least make it optional.

**Comment by paplorinc** [comment]
These are specific to the GPTs, not general tokenization

**Comment by domschl** [comment]
Thank you for all the excellent work!
