### ISSUE TITLE
Need train_multi.py example to show use with multiple input files

### ISSUE THREAD

**Issue by gnp** [karpathy/minbpe#47]
Since there are significant concerns about handling `<|endoftext|>`, there should be an example program that shows how to properly prepare input text for that case and pass to the train function and check that the trained tokenizer is as intended.

**Comment by gnp** [comment]
For example, _test_tokenizer.py_ is written as if `<|endoftext|>' doesn't belong at the end of each input document, or in between input documents, but rather at the start of each input document, which is surprising given its name.

And the example should show what transformations should be made to all the input documents before concatenating them to make them safe to use, even if they contain the string `<|endoftext|>` in them.

Or, training should take a sequence of texts so that no special token is needed.

It is not clear from the examples how to safely use the tokenizer.

**Comment by karpathy** [comment]
When you're training you don't care about special tokens usually, to create training data you'd directly insert the token ids as integers in between documents instead of changing the text to contain <|endoftext|> or something like that.

**Comment by gnp** [comment]
This is in response to [part of your video about the tokenizer](https://www.youtube.com/watch?v=zduSFxRajkE&t=1h57m19s). And, that does affect tokenizer training and evaluation and causes "footguns" if I've understood your presentation correctly.
